apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: default
  labels:
    app: example-app
    test: test
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: example-app
    image: aimvector/python:1.0.4
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: api_key
    volumeMounts:
    - name: secret-volume
      mountPath: /secrets/
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret