apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
  labels:
    app: example-app
type: Opaque
data:
  api_key: c29tZXNlY3JldGdvZXNoZXJlCg==
  secret.json: ew0KICAiYXBpX2tleSIgOiAic29tZXNlY3JldGdvZXNoZXJlIg0KfQ==
# stringData:
#   secret.json: |-
#     {
#       "api_key" : "somesecretgoeshere"
#     }


#kubectl create secret generic mysecret --from-file .\golang\secrets\secret.json