apiVersion: compute.azure.upbound.io/v1beta2
kind: LinuxVirtualMachine
metadata:
  labels:
    app: marcel-test
  name: marcel-test
spec:
  forProvider:
    resourceGroupName: marcel-test
    adminSshKey:
    - publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+wWK73dCr+jgQOAxNsHAnNNNMEMWOHYEccp6wJm2gotpr9katuF/ZAdou5AaW1C61slRkHRkpRRX9FA9CYBiitZgvCCz+3nWNN7l/Up54Zps/pHWGZLHNJZRYyAB6j5yVLMVHIHriY49d/GZTZVNB8GoJv9Gakwc/fuEZYYl4YDFiGMBP///TzlI4jhiJzjKnEvqPFki5p2ZRJqcbCiF4pJrxUQR/RXqVFQdbRLZgYfJ8xGB878RENq3yQ39d8dVOkq4edbkzwcUmwwwkYVPIoDGsYLaRHnG+To7FvMeyO7xDVQkMKzopTQV8AuKpyvpqu0a9pWOMaiCyDytO7GGN
        you@me.com
      username: adminuser
    adminUsername: adminuser
    location: "AustraliaEast"
    networkInterfaceIdsRefs:
    - name: marcel-test
    osDisk:
      caching: ReadWrite
      storageAccountType: Standard_LRS
    size: Standard_F2
    sourceImageReference:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest